### PR TITLE
Vendor dependencies, update README.md.

### PR DESCRIPTION
**Pull request by ojongerius**

### CODE REVIEW

**Comment by BrianHicks** [comment]
Thanks, why did you choose godeps for this? We've been using Glide for Asteris projects, when possible, but I'd love to know why you prefer godep?

**Comment by ojongerius** [comment]
No other reason but familiarity. Glide looks pretty good, do you prefer it, and if so, why? I'll close this PR if you want to go with Glide. :smile:

**Comment by BrianHicks** [comment]
Sorry this has been hanging open so long! I prefer glide because the interface is better, and I've been frustrated by godep in the past. I've added vendoring to master, any 1.6+ compiler will be able to get stuff in `vendor/` now. Thanks again for bringing this up!

**Comment by ojongerius** [comment]
:+1:

**Pull request closed without merging**
